config/routes.rb
BundyClock::Application.routes.draw do
  post "time_logs/time_in", as: :time_in

  put "time_logs/update", as: :update

  put "time_logs/time_out", as: :time_out

  get "/login" => "sessions#new", as: :login

  get "/logout" => "sessions#destroy", as: :logout

  match "/auth/:provider/callback" => "sessions#create"

  match "/auth/failure" => "sessions#failure"

  get "/month" => "time_logs#month"

  get "/month/:date" => "time_logs#month", as: :month

  get "/archive" => "time_logs#archive", as: :archive

  get "/leaves/leave_type" => "leaves#leave_type", as: :leave_type

  resources :leaves, except: [:edit, :update]

  get "/leaves/:date/edit" => "leaves#edit", as: :edit_leave
  put "/leaves/:date" => "leaves#update", as: :update_leave

  resources :users

  resources :time_logs

  get "/me" => "users#settings", as: :settings

  root :to => 'home#index'

end

app/models/time_log.rb
class TimeLog < ActiveRecord::Base
  LEAVE_TYPES = %w[emergency sick vacation]

  has_many :comments
  belongs_to :user

  attr_writer :comment_text

  validates :date, uniqueness: {
    scope: :user_id,
    message: "user should have only one time log per date" },
    on: :create

  def hours
    if out
      (out - self.in) / 60 / 60
    end
  end

  def user_name
    user.name
  end

  def user_email
    user.email
  end

  def comment_text
    @comment_text ||= if comments.any?
      comments.collect(&:comments).join("\n")
    else
      nil
    end
  end

private

  after_save :create_comment_text
  def create_comment_text
    self.comments.create(comments: @comment_text) if @comment_text
  end
end

app/controllers/time_logs_controller.rb
class TimeLogsController < ApplicationController

  before_filter :ensure_logged_in_via_api, only: [:index]

  include DateHelpers

  # GET /time_logs
  # Returns time logs.
  #
  # You may pass `from` and `to` dates, though both are optional.
  #
  # ### Example
  #
  #     bundy.co/time_log?from=2012-03-01
  #     bundy.co/time_log?from=2012-03-01&to=2012-04-05
  #
  def index

    @time_logs = TimeLog
    @time_logs = @time_logs.where('date >= ?', Date.parse(params[:from]))  if params[:from]
    @time_logs = @time_logs.where('date <= ?', Date.parse(params[:to]))  if params[:to]
    @time_logs = @time_logs.all

    respond_to do |format|
      format.json { render json: @time_logs.to_json(methods: [:user_name, :user_email, :comment_text]) }
    end
  end

  # POST /time_logs/time_in
  def time_in 
    @time_log = current_user.time_logs.create date: today, in: Time.now

    if @time_log.valid?
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render file: 'shared/js_error' }
      end
    end
  end

  # PUT /time_logs/time_out
  def time_out
    current_user.current_time_log.update_attributes out: Time.now

    respond_to do |format|
      format.js { render :time_in }
    end
  end

  # PUT /time_logs/update
  def update
    @user = current_user
    @date = Date.parse(params[:time_log][:date]) || today
    @log = @user.time_logs.find_or_initialize_by_date(@date)

    @log.update_attributes params[:time_log]

    @partial = case params[:row_format]
      when 'month' then "month_row"
      when 'user' then "users/row"
      else "home/row"
    end

    respond_to do |format|
      format.js
    end
  end

  def month
    @date = params[:date].nil? ? today : Date.parse(params[:date])
    @year = @date.year
    @month = @date.month
    end_date = Date.civil(@year, @month, -1).day
    end_date = today.day  if @date == today
    @days = (1..end_date)
    @dates = @days.map { |d| Date.parse "#{@year}-#{@month}-#{d}" }
    @users = User.order('name')
  end

  def archive
    @users = User.order('name')
    @dates = range_of_months
  end

end

app/views/time_logs/_month_row.html.haml
%tr{ id: row_id(date, user) }
  
  - time_log = user.time_log_for(date)

  %td.user= link_to user.name, user
  
  %td.in

    - if user == current_user
      - if user.timed_in?(date)
        %a.time{href: "#"}
          = short_time time_log.in

      - else
        %a.time{href: "#"}
          No time in 
  
    - else
      - if user.timed_in?(date)
        = short_time time_log.in
  
      - else
        No time in
  
  %td.out
  
    - if user == current_user
      - if user.timed_out?(date)
        %a.time{href: "#"}
          = short_time time_log.out
  
      - elsif user.timed_in?(date)
        %a.time{href: "#"}
          No time out
  
    - else
      - if user.timed_out?(date)
        = short_time time_log.out

      - elsif user.timed_in?(date)
        No time out

  %td.leave
    = render partial: 'leaves/leave_column', |
      locals: { time_log: time_log, user: user, date: date } |

app/views/time_logs/_row_month.html.haml
%tr{ id: row_id(date, user) }
  
  - time_log = user.time_logs.find_by_date(date)

  %td.user= link_to user.name, user
  
  %td.in

    - if user == current_user
      - if user.timed_in?(date)
        %a.time{href: "#"}
          = short_time time_log.in

      - else
        %a.time{href: "#"}
          No time in 
  
    - else
      - if user.timed_in?(date)
        = short_time time_log.in
  
      - else
        No time in
  
  %td.out
  
    - if user == current_user
      - if user.timed_out?(date)
        %a.time{href: "#"}
          = short_time time_log.out
  
      - elsif user.timed_in?(date)
        %a.time{href: "#"}
          No time out
  
    - else
      - if user.timed_out?(date)
        = short_time time_log.out

      - elsif user.timed_in?(date)
        No time out

app/views/time_logs/archive.html.haml
- section :archive
%section.archive

  %hgroup
    %h3 Archive

  %table

    - @dates.each do |date|

      %tr
        %th= date.to_s(:month_year)

        - @users.each do |user|
          %td
            = link_to user.name, user_path(user, date: date)

        %td 
          = link_to "All", month_path(date: date)

app/views/time_logs/month.html.haml
- section :month

%section.month

  %h3= @date.to_s(:month_year)

  - @dates.each do |date|

    %h4
      = date.to_s(:daily)

    %table.month{data: { date: date.strftime("%Y/%m/%d") } }

      - @users.each do |user|
        = render partial: 'month_row', locals: { date: date, user: user } 

    %br
    %br

app/views/time_logs/time_in.js.erb
$('tr#<%= row_id(today, current_user) %>').replaceWith(
    <%= render(partial: 'home/row',
      locals: { user: current_user, date: today }).to_json.html_safe %>);

app/views/time_logs/time_out.js.erb
$('tr.<%= current_user.id %>').replaceWith(
    <%= render(partial: 'home/row',
      locals: { user: current_user }).to_json.html_safe %>);

app/views/time_logs/update.js.erb
$('tr#<%= row_id(@date, current_user) %>').replaceWith(
    <%= render(partial: @partial,
      locals: { date: @date, user: current_user }).to_json.html_safe %>);