config/routes.rb
BundyClock::Application.routes.draw do
  post "time_logs/time_in", as: :time_in

  put "time_logs/update", as: :update

  put "time_logs/time_out", as: :time_out

  get "/login" => "sessions#new", as: :login

  get "/logout" => "sessions#destroy", as: :logout

  match "/auth/:provider/callback" => "sessions#create"

  match "/auth/failure" => "sessions#failure"

  get "/month" => "time_logs#month"

  get "/month/:date" => "time_logs#month", as: :month

  get "/archive" => "time_logs#archive", as: :archive

  get "/leaves/leave_type" => "leaves#leave_type", as: :leave_type

  resources :leaves, except: [:edit, :update]

  get "/leaves/:date/edit" => "leaves#edit", as: :edit_leave
  put "/leaves/:date" => "leaves#update", as: :update_leave

  resources :users

  resources :time_logs

  get "/me" => "users#settings", as: :settings

  root :to => 'home#index'

end

app/models/user.rb
# Example
#
#   u = User.find_by_email('benj@nadarei.co')
#
#   u.name    #=> "Benj"
#   u.email   #=> "benj@nadarei.co"
#
#   u.on_leave?(today)    #=> true
#
class User < ActiveRecord::Base

  validates :name, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: true

  has_many :time_logs, order: :date do
    def hours
      hours = 0
      self.each {|log| hours += log.hours if log.hours}
      hours
    end
  end

  include Calendar
  include DateHelpers

  def time_log_for(date=today)
    # self.time_logs.where(date: date).first
    self.time_logs.find_by_date(date)
  end

  def timed_in?(date)
    log = time_log_for(date)
    log && log.in
  end

  def must_time_out?(date)
    log = time_log_for(date)
    log && !log.out
  end

  def timed_out?(date)
    log = time_log_for(date)
    log && log.out
  end
  
  def any_comments?(date=today)
    log = time_log_for(date)
    log && log.comments
  end

  def working_day?(date)
    if timed_in?(date)
      true
    else
      ! no_work?(date)
    end
  end

  # Old behavior below!
  
  def current_time_log
    time_log_for today
  end

  def timed_in_today?
    timed_in? today
  end

  def must_time_out_today?
    must_time_out? today
  end

  def timed_out_today?
    timed_out? today
  end

  before_create :generate_api_key
  def generate_api_key(force=true)
    return  if self.api_key && !force
    self.api_key = "%064x" % rand(2**256)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :ensure_logged_in, except: [:index]

  include DateHelpers

  def index
    redirect_to root_url
  end

  def show
    @user = User.find(params[:id])

    @date = params[:date].nil? ? today : Date.parse(params[:date])

    @dates_of_month = range_for_month_with(@date)

    time_logs_of_month = @user.time_logs.where("date >= ? and date <= ?",
                                               @dates_of_month.begin,
                                               @dates_of_month.end)

    @total_hours = time_logs_of_month.hours
  end

  def settings
    @user = current_user
  end
end

app/views/users/_row.html.haml
- time_log = @user.time_log_for(date)

%tr{ id: row_id(date, @user), data: { date: date.strftime("%Y/%m/%d") } }

  %td.date= date.strftime("%a %d")

  %td.in

    - if @user == current_user
      - if @user.timed_in?(date)
        %a.time{href: "#"}
          = short_time time_log.in
      
      - else
        %a.time{href: "#"}
          = "No time in"

    - else
      - if @user.timed_in?(date)
        = short_time time_log.in

      - else
        = "No time in"

  %td.out

    - if @user == current_user
      - if @user.timed_out?(date)
        %a.time{href: "#"}
          = short_time time_log.out
      
      - else
        %a.time{href: "#"}
          = "No time out"

    - else
      - if @user.timed_out?(date)
        = short_time time_log.out
      
      - else
        = "No time out"

  %td.comment
    = render partial: 'comments/comments', locals: { user: @user, date: date }

  %td.hours
    - if time_log && time_log.hours
      = time_log.hours.round(2)
    - else
      = "-"

  %td.leave
    = render partial: 'leaves/leave_column', |
      locals: { time_log: time_log, user: @user, date: date } |

app/views/users/settings.html.haml
%section.settings
  %form
    %label
      Your API key:
    %input{type: 'text', value: @user.api_key}

    %p
      You may access the API using:

    %ul
      %li
        %code= time_logs_url + "?api_key=YOUR_KEY"
      %li
        %code= time_logs_url + "?api_key=YOUR_KEY&from=2012-03-31&to=2012-04-04"

app/views/users/show.html.haml
%section.user
  %hgroup
    %h3= @user.name
    %p= @date.to_s(:month_year)

  %table
    %tr
      %th Date
      %th Time In
      %th Time Out
      %th Comments
      %th Hours
      %th Leaves

    - @dates_of_month.each do |date|
      = render partial: 'row', locals: {user: @user, date: date}

    %tr.total
      %td
        %strong Total Hours
      %td
      %td
      %td
      %td.hours
        %strong= @total_hours.round(2)
      %td