config/routes.rb
BundyClock::Application.routes.draw do
  post "time_logs/time_in", as: :time_in

  put "time_logs/update", as: :update

  put "time_logs/time_out", as: :time_out

  get "/login" => "sessions#new", as: :login

  get "/logout" => "sessions#destroy", as: :logout

  match "/auth/:provider/callback" => "sessions#create"

  match "/auth/failure" => "sessions#failure"

  get "/month" => "time_logs#month"

  get "/month/:date" => "time_logs#month", as: :month

  get "/archive" => "time_logs#archive", as: :archive

  get "/leaves/leave_type" => "leaves#leave_type", as: :leave_type

  resources :leaves, except: [:edit, :update]

  get "/leaves/:date/edit" => "leaves#edit", as: :edit_leave
  put "/leaves/:date" => "leaves#update", as: :update_leave

  resources :users

  resources :time_logs

  get "/me" => "users#settings", as: :settings

  root :to => 'home#index'

end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
  before_filter :ensure_logged_in, only: [:index]

  def new
    @time_log = current_user.time_logs.new
  end

  def leave_type
    @time_log = current_user.time_logs.find_or_initialize_by_date(params[:date])

    respond_to do |format|
      format.js
    end
  end

  def create
    @time_log = current_user.time_logs.find_or_initialize_by_date(params[:date])

    new_record = @time_log.new_record?

    if @time_log.update_attributes params[:time_log]
      flash[:notice] = new_record ? "New leave filed" : "Leave updated"
      redirect_to user_path(current_user, date: params[:date])
    else
      render :new
    end
  end

  def edit
    @time_log = current_user.time_logs.find_or_initialize_by_date(params[:date])

    respond_to do |format|
      format.js
    end
  end

  def update
    @time_log = current_user.time_logs.find_or_initialize_by_date(params[:date])

    @time_log.update_attributes params[:time_log]

    respond_to do |format|
      format.js
    end
  end
end

app/views/leaves/_form.html.haml
%h3 Select leave:
= form_for time_log, url: update_leave_path, remote: true do |f|
  = render partial: 'leave_type', locals: { time_log: time_log }

  %fieldset.actions
    = f.submit "Save"

app/views/leaves/_leave_column.html.haml
- if time_log && time_log.leave_type
  = link_to time_log.leave_type

- elsif user == current_user && user.absent_or_half_day?(date)

  = link_to "File leave", |
    { action: 'edit', controller: 'leaves', date: date }, remote: true |

app/views/leaves/_leave_type.html.haml
%fieldset.leave-type
  %h4 Leave type:
  = fields_for time_log do |f|
    - TimeLog::LEAVE_TYPES.each do |type|
      %fieldset.field
        = f.radio_button 'leave_type', type
        = f.label "leave_type_#{type}", type.capitalize

  %fieldset.field
    = check_box 'time_log', 'leave_duration', { checked: 'unchecked' }, '0.5', '1.0'
    = label 'time_log', 'leave_duration', "Half day?"

app/views/leaves/create.html.haml
- section :created_leave
%section.created_leave

  %h3 Leave filed

  %table.leave
    %tr
      %td.date= @time_log.date.strftime("%Y/%m/%d")
      %td.leave
        = render partial: 'leave_column', locals: { time_log: @time_log, user: current_user, date: @time_log.date }

app/views/leaves/create.js.erb
$.facebox(
    <%= render(partial: 'leaves/form',
      locals: { time_log: @time_log }).to_json.html_safe %>)

app/views/leaves/edit.js.erb
$.facebox(
    <%= render(partial: 'leaves/form',
      locals: { time_log: @time_log }).to_json.html_safe %>)

app/views/leaves/leave_type.js.erb
$('fieldset:not(.date)').show();
$('fieldset.leave-type').replaceWith(
    <%= render(partial: "leave_type", locals: { time_log: @time_log }).to_json.html_safe %>);

app/views/leaves/new.html.haml
- section :leave
%section.leave

  %h3 File leave

  = form_for @time_log, url: leaves_path do |f|

    %fieldset.date
      %h4 Effective date:
      = text_field_tag 'date', nil, { size: 11, id: 'datepicker' }

    = render partial: 'leave_type', locals: { time_log: @time_log }

    %fieldset.actions
      = f.submit "Submit"

app/views/leaves/update.js.erb
$(document).trigger('close.facebox');
$('tr#<%= row_id(@time_log.date, current_user) %>')
  .find('td.leave')
  .html(
      <%= render(partial: 'leave_column',
        locals: { time_log: @time_log }).to_json.html_safe %>);